//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Возврат билета.
    /// </summary>
    // *** Start programmer edit section *** (ВозвратБилета CustomAttributes)

    // *** End programmer edit section *** (ВозвратБилета CustomAttributes)
    [AutoAltered()]
    [Caption("Возврат билета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВозвратБилетаE", new string[] {
            "ДатаВозврата as \'Дата возврата\'",
            "ПокупкаБилета as \'Покупка билета\'",
            "ПокупкаБилета.ДатаПокупки as \'Дата покупки\'",
            "ПокупкаБилета.ПунктОтправ as \'Пункт отправления\'",
            "ПокупкаБилета.ПунктНазнач as \'Пункт назначения\'",
            "ПокупкаБилета.Место as \'Место\'",
            "ПокупкаБилета.Перевозчик.Наименование as \'Перевозчик\'",
            "ПокупкаБилета.Покупатель.ФИО as \'Покупатель\'",
            "ПокупкаБилета.Покупатель.БанковскийСчет as \'Банковский счет\'",
            "ПокупкаБилета.БилетнаяКасса.Наименование as \'Место расчета\'"})]
    [MasterViewDefineAttribute("ВозвратБилетаE", "ПокупкаБилета", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ПунктОтправ")]
    [View("ВозвратБилетаL", new string[] {
            "ДатаВозврата as \'Дата возврата\'",
            "ПокупкаБилета.ДатаПокупки as \'Дата покупки\'",
            "ПокупкаБилета.ПунктОтправ as \'Пункт отправления\'",
            "ПокупкаБилета.ПунктНазнач as \'пункт назначения\'",
            "ПокупкаБилета.Место as \'Место\'",
            "ПокупкаБилета.Перевозчик.Наименование as \'Перевозчик\'",
            "ПокупкаБилета.Покупатель.ФИО as \'Покупатель\'",
            "ПокупкаБилета.Покупатель.БанковскийСчет as \'Банковский счет\'",
            "ПокупкаБилета.БилетнаяКасса.Наименование as \'Место расчета\'"})]
    public class ВозвратБилета : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаВозврата = System.DateTime.Now;
        
        private IIS.Kyrs6.ПокупкаБилета fПокупкаБилета;
        
        // *** Start programmer edit section *** (ВозвратБилета CustomMembers)

        // *** End programmer edit section *** (ВозвратБилета CustomMembers)

        
        /// <summary>
        /// ДатаВозврата.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата CustomAttributes)

        // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата CustomAttributes)
        public virtual System.DateTime ДатаВозврата
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата Get start)

                // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата Get start)
                System.DateTime result = this.fДатаВозврата;
                // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата Get end)

                // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата Set start)

                // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата Set start)
                this.fДатаВозврата = value;
                // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата Set end)

                // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата Set end)
            }
        }
        
        /// <summary>
        /// Возврат билета.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета CustomAttributes)

        // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета CustomAttributes)
        [PropertyStorage(new string[] {
                "ПокупкаБилета"})]
        [NotNull()]
        public virtual IIS.Kyrs6.ПокупкаБилета ПокупкаБилета
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета Get start)

                // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета Get start)
                IIS.Kyrs6.ПокупкаБилета result = this.fПокупкаБилета;
                // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета Get end)

                // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета Set start)

                // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета Set start)
                this.fПокупкаБилета = value;
                // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета Set end)

                // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВозвратБилетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВозвратБилетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВозвратБилетаE", typeof(IIS.Kyrs6.ВозвратБилета));
                }
            }
            
            /// <summary>
            /// "ВозвратБилетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВозвратБилетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВозвратБилетаL", typeof(IIS.Kyrs6.ВозвратБилета));
                }
            }
        }
    }
}
