//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплата билета.
    /// </summary>
    // *** Start programmer edit section *** (ОплатаБилета CustomAttributes)

    // *** End programmer edit section *** (ОплатаБилета CustomAttributes)
    [AutoAltered()]
    [Caption("Оплата билета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОплатаБилетаE", new string[] {
            "ДатаОплаты as \'Дата оплаты\'",
            "ПокупкаБилета as \'Покупка билета\'",
            "ПокупкаБилета.Покупатель.ФИО as \'Покупатель\'",
            "ПокупкаБилета.Покупатель.БанковскийСчет as \'Банковский счет\'",
            "ПокупкаБилета.БилетнаяКасса.Наименование as \'Место расчета\'"})]
    [MasterViewDefineAttribute("ОплатаБилетаE", "ПокупкаБилета", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ПунктОтправ")]
    [View("ОплатаБилетаL", new string[] {
            "ДатаОплаты as \'Дата оплаты\'",
            "ПокупкаБилета.Покупатель.ФИО as \'Покупатель\'",
            "ПокупкаБилета.БилетнаяКасса.Наименование as \'Место расчета\'",
            "ПокупкаБилета.Покупатель.БанковскийСчет as \'Банковский счет\'"})]
    public class ОплатаБилета : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОплаты = System.DateTime.Now;
        
        private IIS.Kyrs6.ПокупкаБилета fПокупкаБилета;
        
        // *** Start programmer edit section *** (ОплатаБилета CustomMembers)

        // *** End programmer edit section *** (ОплатаБилета CustomMembers)

        
        /// <summary>
        /// ДатаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (ОплатаБилета.ДатаОплаты CustomAttributes)

        // *** End programmer edit section *** (ОплатаБилета.ДатаОплаты CustomAttributes)
        public virtual System.DateTime ДатаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (ОплатаБилета.ДатаОплаты Get start)

                // *** End programmer edit section *** (ОплатаБилета.ДатаОплаты Get start)
                System.DateTime result = this.fДатаОплаты;
                // *** Start programmer edit section *** (ОплатаБилета.ДатаОплаты Get end)

                // *** End programmer edit section *** (ОплатаБилета.ДатаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОплатаБилета.ДатаОплаты Set start)

                // *** End programmer edit section *** (ОплатаБилета.ДатаОплаты Set start)
                this.fДатаОплаты = value;
                // *** Start programmer edit section *** (ОплатаБилета.ДатаОплаты Set end)

                // *** End programmer edit section *** (ОплатаБилета.ДатаОплаты Set end)
            }
        }
        
        /// <summary>
        /// Оплата билета.
        /// </summary>
        // *** Start programmer edit section *** (ОплатаБилета.ПокупкаБилета CustomAttributes)

        // *** End programmer edit section *** (ОплатаБилета.ПокупкаБилета CustomAttributes)
        [PropertyStorage(new string[] {
                "ПокупкаБилета"})]
        [NotNull()]
        public virtual IIS.Kyrs6.ПокупкаБилета ПокупкаБилета
        {
            get
            {
                // *** Start programmer edit section *** (ОплатаБилета.ПокупкаБилета Get start)

                // *** End programmer edit section *** (ОплатаБилета.ПокупкаБилета Get start)
                IIS.Kyrs6.ПокупкаБилета result = this.fПокупкаБилета;
                // *** Start programmer edit section *** (ОплатаБилета.ПокупкаБилета Get end)

                // *** End programmer edit section *** (ОплатаБилета.ПокупкаБилета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОплатаБилета.ПокупкаБилета Set start)

                // *** End programmer edit section *** (ОплатаБилета.ПокупкаБилета Set start)
                this.fПокупкаБилета = value;
                // *** Start programmer edit section *** (ОплатаБилета.ПокупкаБилета Set end)

                // *** End programmer edit section *** (ОплатаБилета.ПокупкаБилета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОплатаБилетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаБилетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаБилетаE", typeof(IIS.Kyrs6.ОплатаБилета));
                }
            }
            
            /// <summary>
            /// "ОплатаБилетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаБилетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаБилетаL", typeof(IIS.Kyrs6.ОплатаБилета));
                }
            }
        }
    }
}
