//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs6
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус.
    /// </summary>
    // *** Start programmer edit section *** (Статус CustomAttributes)

    // *** End programmer edit section *** (Статус CustomAttributes)
    public enum Статус
    {
        
        // *** Start programmer edit section *** (Статус.Оплачен CustomAttributes)

        // *** End programmer edit section *** (Статус.Оплачен CustomAttributes)
        Оплачен,
        
        // *** Start programmer edit section *** (Статус.Возврат CustomAttributes)

        // *** End programmer edit section *** (Статус.Возврат CustomAttributes)
        Возврат,
        
        // *** Start programmer edit section *** (Статус.НеОплачен CustomAttributes)

        // *** End programmer edit section *** (Статус.НеОплачен CustomAttributes)
        НеОплачен,
    }
}
