




CREATE TABLE ВозвратБилета (
 primaryKey UUID NOT NULL,
 ДатаВозврата TIMESTAMP(3) NULL,
 ПокупкаБилета UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ПокупкаБилета (
 primaryKey UUID NOT NULL,
 ПунктОтправ VARCHAR(255) NULL,
 Место INT NULL,
 ДатаПоездки TIMESTAMP(3) NULL,
 ДатаПокупки TIMESTAMP(3) NULL,
 ПунктНазнач VARCHAR(255) NULL,
 ВремяПокупки VARCHAR(255) NULL,
 Статус VARCHAR(9) NULL,
 БилетнаяКасса UUID NOT NULL,
 Покупатель UUID NOT NULL,
 Перевозчик UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Покупатель (
 primaryKey UUID NOT NULL,
 БанковскийСчет VARCHAR(255) NULL,
 ID INT NULL,
 ФИО VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE БилетнаяКасса (
 primaryKey UUID NOT NULL,
 Наименование VARCHAR(255) NULL,
 Адрес VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Перевозчик (
 primaryKey UUID NOT NULL,
 Наименование VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ОплатаБилета (
 primaryKey UUID NOT NULL,
 ДатаОплаты TIMESTAMP(3) NULL,
 ПокупкаБилета UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE ВозвратБилета ADD CONSTRAINT FK6a9cc057120f106491aea2364a7b7e5bbcbff732 FOREIGN KEY (ПокупкаБилета) REFERENCES ПокупкаБилета; 
CREATE INDEX Index6a9cc057120f106491aea2364a7b7e5bbcbff732 on ВозвратБилета (ПокупкаБилета); 

 ALTER TABLE ПокупкаБилета ADD CONSTRAINT FKbf717e0531e3b2f44fbc863177f66228a17e7f96 FOREIGN KEY (БилетнаяКасса) REFERENCES БилетнаяКасса; 
CREATE INDEX Indexbf717e0531e3b2f44fbc863177f66228a17e7f96 on ПокупкаБилета (БилетнаяКасса); 

 ALTER TABLE ПокупкаБилета ADD CONSTRAINT FK0d61acab3d422c47721e1ae739862bfd7d958709 FOREIGN KEY (Покупатель) REFERENCES Покупатель; 
CREATE INDEX Index0d61acab3d422c47721e1ae739862bfd7d958709 on ПокупкаБилета (Покупатель); 

 ALTER TABLE ПокупкаБилета ADD CONSTRAINT FK358ec4d2785123eb6a977568614da525c2b186ea FOREIGN KEY (Перевозчик) REFERENCES Перевозчик; 
CREATE INDEX Index358ec4d2785123eb6a977568614da525c2b186ea on ПокупкаБилета (Перевозчик); 

 ALTER TABLE ОплатаБилета ADD CONSTRAINT FKba9fc4acdb879647970810b8266879fda8975044 FOREIGN KEY (ПокупкаБилета) REFERENCES ПокупкаБилета; 
CREATE INDEX Indexba9fc4acdb879647970810b8266879fda8975044 on ОплатаБилета (ПокупкаБилета); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

